---
- hosts: localhost
  tasks:
    - name: create namespace
      kubernetes.core.k8s:
        name: "{{ name_space_name }}"
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy the app
      kubernetes.core.k8s:
        state: present
        validate_certs: no
        namespace: "{{ name_space_name }}"
        definition: "{{ lookup('template', 'deployment.yml') | from_yaml }}"
    - name: Deploy the service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
        validate_certs: no
        namespace: "{{ name_space_name }}"
         
