---
- name: build and push to Dockerhub
  hosts: kmaster
  become: true
  gather_facts: false
 
  tasks:
    - name: Push Docker image to Registry
      docker_image:
        name: ABC_tech_image
        build:
          path: /home/edureka/Destop/docker
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: "{{ docker_reg }}:{{ items }}"
        with_items:
          - "{{ TAG }}"
          - latest
        push: yes
        source: build
