---
- name: build and run Docker
  hosts: all
  become: true
  gather_facts: false
 
  tasks:
    - name: Build a Docker image using webapp.war file
      docker_image:
        name: abc-tech-image
        build:
          path: /home/edureka/Desktop/docker
          pull: false
        source: build
 
    - name: Run Docker container using dockerimage
      docker_container:
        name: abc-tech-container
        image: abc-tech-image:latest
        state: started
        recreate: yes
        detach: true
        ports:
          - "8888:8080"
