---
- name: build and push to Dockerhub
  hosts: kmaster
  become: true
  gather_facts: false
 
  tasks:
    - name: Push Docker image to Registry
      docker_image:
        name: ABC_tech_image
        build:
          path: .
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: "{{ docker_reg }}:latest"
        #with_items: "{{ TAG }}"
        push: yes
        source: build
