apiVersion: v1
kind: Service
metadata:
    name: "{{ name_space_name }}-srv"
    namespace: "{{ name_space_name }}"
    labels:
        app: "{{ name_space_name }}-app"
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30036
      protocol: TCP
      targetport: 8080
      name: http
  selector:
    app: "{{ name_space_name }}-app"
